
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame3")
fuente=("Righteous Regular", 15)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def regresar():
    window.destroy()
    subprocess.Popen('python principal.py', shell=True)

window = Tk()

window.geometry("700x550")
window.configure(bg = "#ECECC4")


canvas = Canvas(
    window,
    bg = "#ECECC4",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    87.0,
    fill="#F1C40F",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=248.0,
    y=462.0,
    width=202.0,
    height=58.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    445.0,
    159.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F2DD88",
    fg="#947A1F",
    highlightthickness=0,
    font=fuente,
    
)
entry_1.place(
    x=302.0,
    y=133.0,
    width=286.0,
    height=50.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    445.0,
    239.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F2DD88",
    fg="#947A1F",
    highlightthickness=0,
    font=fuente
    
)
entry_2.place(
    x=302.0,
    y=213.0,
    width=286.0,
    height=50.0
)

canvas.create_text(
    214.0,
    6.0,
    anchor="nw",
    text="Agregar",
    fill="#F5F5DC",
    font=("Righteous Regular", 70 * -1)
)

canvas.create_text(
    121.0,
    141.0,
    anchor="nw",
    text="Titulo:",
    fill="#E67E22",
    font=("Righteous Regular", 30 * -1)
)

canvas.create_text(
    122.0,
    390.0,
    anchor="nw",
    text="Año:",
    fill="#E67E22",
    font=("Righteous Regular", 30 * -1)
)

canvas.create_text(
    111.0,
    306.0,
    anchor="nw",
    text="Genero:",
    fill="#E67E22",
    font=("Righteous Regular", 30 * -1)
)

canvas.create_text(
    121.0,
    221.0,
    anchor="nw",
    text="Autor:",
    fill="#E67E22",
    font=("Righteous Regular", 30 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    445.0,
    324.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#F2DD88",
    fg="#947A1F",
    highlightthickness=0,
    font=fuente
)
entry_3.place(
    x=302.0,
    y=298.0,
    width=286.0,
    height=50.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    445.0,
    408.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#F2DD88",
    fg="#947A1F",
    highlightthickness=0,
    font=fuente
)
entry_4.place(
    x=302.0,
    y=382.0,
    width=286.0,
    height=50.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    255.0,
    239.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    255.0,
    160.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    255.0,
    324.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    255.0,
    408.0,
    image=image_image_4
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=regresar,
    relief="flat"
)
button_2.place(
    x=16.0,
    y=4.0,
    width=72.0,
    height=79.0
)
window.resizable(False, False)
window.mainloop()
