
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def regresar():
    window.destroy()
    subprocess.Popen('python principal.py', shell=True)


window = Tk()
fuente=("Righteous Regular", 25)
window.title("Buscar")
window.geometry("700x550")
window.configure(bg = "#F5F5DC")


canvas = Canvas(
    window,
    bg = "#F5F5DC",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    2.0,
    700.0,
    89.0,
    fill="#F1C40F",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=regresar,
    relief="flat"
)
button_1.place(
    x=16.0,
    y=5.0,
    width=72.0,
    height=79.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    349.5,
    363.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F2DD88",
    fg="#947A1F",
    highlightthickness=0,
    font=fuente,
    justify="center"
)
entry_1.place(
    x=148.0,
    y=329.0,
    width=403.0,
    height=66.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    349.0,
    260.0,
    image=image_image_1
)

canvas.create_text(
    174.0,
    146.0,
    anchor="nw",
    text="Buscar por titulo o autor",
    fill="#E67E22",
    font=("Righteous Regular", 30 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=249.0,
    y=434.0,
    width=202.0,
    height=58.0
)

canvas.create_text(
    234.0,
    5.0,
    anchor="nw",
    text="Buscar",
    fill="#F5F5DC",
    font=("Righteous Regular", 70 * -1)
)
window.resizable(False, False)
window.mainloop()
