
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import END, Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess
import csv

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame1")

#CLASE LIBRO
class Libro:
    def __init__(self, titulo, autor, genero, anio_publicacion, estado):
        self.titulo = titulo
        self.autor = autor
        self.genero = genero
        self.anio_publicacion = anio_publicacion
        self.estado = estado

# Definición de la clase Biblioteca
class Biblioteca: 
    def __init__(self):
        self.libros = []
        self.cargar_csv()

    def agregar_libro(self, libro):
        self.libros.append(libro)
        self.guardar_en_csv(libro)
        print("\nLibro registrado con éxito.")

    def cargar_csv(self):
        try:
            with open('biblioteca.csv', mode='r', newline='', encoding='utf-8') as file:
                reader = csv.reader(file)
                for row in reader:
                    if len(row) == 5:
                        libro = Libro(row[0], row[1], row[2], row[3], row[4])
                        self.libros.append(libro)
        except FileNotFoundError:
            pass

    def guardar_en_csv(self, libro):
        with open("biblioteca.csv", mode="a", newline='', encoding='utf-8') as file:
            escribir = csv.writer(file)
            escribir.writerow([libro.titulo, libro.autor, libro.genero, libro.anio_publicacion, libro.estado])

    def reservar_libro(self, titulo_libro):
        for libro in self.libros:
            if libro.titulo.lower() == titulo_libro.lower():
                if libro.estado == "Disponible":
                    libro.estado = "Reservado"
                    self.actualizar_csv()
                    print(f"Libro '{libro.titulo}' reservado con éxito.")
                    return
        print(f"El libro '{titulo_libro}' no se encuentra disponible para reserva.")

    def actualizar_csv(self):
        with open("biblioteca.csv", mode="w", newline='', encoding='utf-8') as file:
            escribir = csv.writer(file)
            for libro in self.libros:
                escribir.writerow([libro.titulo, libro.autor, libro.genero, libro.anio_publicacion, libro.estado])

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def regresar():
    window.destroy()
    subprocess.Popen('python principal.py', shell=True)

biblioteca = Biblioteca()

window = Tk()

window.geometry("700x550")
window.configure(bg = "#ECECC4")
#window.iconbitmap("icono.ico")
window.title("Mostrar")

canvas = Canvas(
    window,
    bg = "#ECECC4",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    347.5,
    274.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F2DD88",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=32.0,
    y=125.0,
    width=631.0,
    height=296.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    87.0,
    fill="#F1C40F",
    outline="")

canvas.create_text(
    220.0,
    0.0,
    anchor="nw",
    text="Mostrar",
    fill="#F5F5DC",
    font=("Righteous Regular", 70 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=regresar,
    relief="flat"
)
button_1.place(
    x=19.0,
    y=3.0,
    width=72.0,
    height=79.0
)
window.resizable(False, False)




def showbk():
    lst = []
    for libro in biblioteca.libros:
        titulo = libro.titulo
        autor = libro.autor
        genero = libro.genero
        anio = libro.anio_publicacion
        estado = libro.estado

        tupla = (titulo,autor,genero,anio,estado)
        lst.append(tupla)

    total_rows = len(lst)
    total_columns = len(lst[0])

    for i in range(total_rows):
            for j in range(total_columns):
                 
                e = Entry(canvas, width=16, fg='black',
                               font=('Arial',11,'bold'))
                 
                e.grid(row=i, column=j)
                e.insert(END, lst[i][j])

showbk()

window.mainloop()
