
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x550")
window.configure(bg = "#ECECC4")
window.iconbitmap("icono.ico")
window.title("Mostrar")

canvas = Canvas(
    window,
    bg = "#ECECC4",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    347.5,
    274.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F2DD88",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=32.0,
    y=125.0,
    width=631.0,
    height=296.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    87.0,
    fill="#F1C40F",
    outline="")

canvas.create_text(
    220.0,
    0.0,
    anchor="nw",
    text="Mostrar",
    fill="#F5F5DC",
    font=("Righteous Regular", 70 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=19.0,
    y=3.0,
    width=72.0,
    height=79.0
)
window.resizable(False, False)
window.mainloop()
